# Generated by Django 3.2.4 on 2023-04-27 01:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230427_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='project',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='client',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='name',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='status',
        ),
        migrations.AddField(
            model_name='incident',
            name='closed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_id',
            field=models.CharField(default=api.models.Incident.create_inc_id, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
