# Generated by Django 3.2.4 on 2023-04-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230427_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='closed_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date_created',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='LOW', max_length=20),
        ),
    ]
