# Generated by Django 3.2.4 on 2023-04-28 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_incident_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
